### PR TITLE
Update to 1.6

### PR DESCRIPTION
**Pull request by Tenebrosful**
#21

### CODE REVIEW

**Comment by Tenebrosful** [comment]
https://github.com/Tenebrosful/StardewValley_UnlimitedPlayers/blob/b9c9642877b520cee1d87276be579d800d019cbd/UnlimitedPlayers/Events/Display/MenuEvents.cs#L18C3-L34C4

I have no idea about this, just knowing that blueprint doesn't exist anymore https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#Other_building_changes

**Comment by RAIDSouL** [comment]
https://github.com/RAIDSouL/StardewValley_UnlimitedPlayers 
I fixed by comment it.

**Comment by Tenebrosful** [comment]
Wasn't it the code that permit to always display cabin when reaching vanilla player limit in Robin's shop ?

**Comment by Tenebrosful** [comment]
Yeah it looks like this code re-add cabin to carpenter shop when there is more than 8 cabins in farm (yes now stardew is 8 player vanilla)

**Comment by Tenebrosful** [comment]
Compiled file if people want

[UnlimitedPlayers-2024.3.29-unofficial.1-tenebrosful.zip](https://github.com/Armitxes/StardewValley_UnlimitedPlayers/files/14798532/UnlimitedPlayers-2024.3.29-unofficial.1-tenebrosful.zip)

**Comment by Armitxes** [comment]
Thanks a lot for your contributions @Tenebrosful  👍 give me a bit to test it

**Pull request merged**
